### ISSUE TITLE
Review command line options vs env var

### ISSUE THREAD

**Issue by domwong** [micro/development#225]
Make sure all command line / env var combinations work as expected. 

Example user report from Slack

@asim just to let you know guys, that some of the command line and environment options for micro server are not working. This is a working configuration that I was able to get it working correctly with docker-compose, using version 2.9.1.

```
micro:
  command:
    - --registry=etcd
    - --registry_address=etcd
    - server
  image: micro/micro:latest
  environment:
    - MICRO_API_NAMESPACE=com.matoski.api
    - MICRO_WEB_NAMESPACE=com.matoski.web
    - MICRO_STORE=cockroach
    - MICRO_STORE_ADDRESS=postgresql://root@cockroach:26257?sslmode=disable
  links:
    - etcd
    - cockroach
  ports:
    - "8080-8082:8080-8082"
These are not working:
--store=cockroach - results in file based store
--store_address=postgresql://root@cockroach:26257?sslmode=disable - results in the default value of postgresql://root@127.0.0.1:26257?sslmode=disable
MICRO_REGISTRY_ADDRESS=etcd - results in the default value and is not able to connect
```
